# Site settings
title: Consistency Till The End. # site title
description: >- # site description
  He's writing in Korean about Data Engineering and experience as a journal 
  for documentation that he learned, meet him <a href="https://github.com/avoholo" target="_blank" rel="noopener">avoholo@github</a>.
lang: en-US # default lang
timezone: Asia/Seoul # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/avoholo # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Avo Tech Blog
  bio: <hr style="height:3px; visibility:hidden;" />
    <p style="font-family:Georgia">“<i>The biggest issue on software teams is making sure</p>
    <p style="font-family:Georgia">everyone understands what everyone else is doing.</i>”</p>
    <hr style="height:2px; visibility:hidden;" />
    <p style="font-family:Georgia;font-weight:10">- Martin Fowler</p>
#    meet 남규 at <a href="https://github.com/avoholo" target="_blank" rel="noopener">@github</a>.
  username: Avoholo # general username
  github: avoholo # github username
  twitter: avoholo # twitter username
  facebook: avoholo # facebook username
  email: jkjohnwuhan@email.com # email adress
  avatar: /assets/img/avatar.jpg # change with your own avatar

# URL settings
url: "https://avoholo.github.io/" #
baseurl:
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 30

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - lighthouse.png

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
